version: 0.2

phases:
  install:
    commands:
      # Install dependencies, Docker, and Packer
      - apt-get update -y
      - apt-get install -y docker.io
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update && apt-get install -y packer

  pre_build:
    commands:
      # Login to Docker Hub using secrets from CodeBuild
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      # Initialize Packer
      - packer init .

  build:
    commands:
      # Validate and build the Docker image using Packer
      - packer validate packer.pkr.hcl
      - packer build packer.pkr.hcl
      # Push Docker image to Docker Hub
      - docker build -t s3cloudhub/my-app:latest .
      - docker push s3cloudhub/my-app:latest

  post_build:
    commands:
      # Logout from Docker Hub
      - docker logout

env:
  secrets-manager:
    DOCKER_USERNAME: <path-to-docker-username-secret>
    DOCKER_PASSWORD: <path-to-docker-password-secret>
