version: 0.2

phases:
  install:
    commands:
      # Install dependencies, Docker, and Packer
     version: 0.2

phases:
  install:
    commands:
      # Use yum instead of apt-get for Amazon Linux
      - yum update -y
      - yum install -y docker
      - yum install -y packer


  pre_build:
    commands:
      # Login to Docker Hub using secrets from CodeBuild
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      # Initialize Packer
      - packer init .

  build:
    commands:
      # Validate and build the Docker image using Packer
      - packer validate packer.pkr.hcl
      - packer build packer.pkr.hcl
      # Push Docker image to Docker Hub
      - docker build -t s3cloudhub/my-app:latest .
      - docker push s3cloudhub/my-app:latest

  post_build:
    commands:
      # Logout from Docker Hub
      - docker logout

env:
  secrets-manager:
    DOCKER_USERNAME: example/demo:DOCKER_USERNAME
    DOCKER_PASSWORD: example/demo:DOCKER_PASSWORD
